import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "../components/SiteHeader";

export const metadata: Metadata = { title: "Innovation Network | HBIVentures", description: "HBI partnerships connect learning, technology, workforce opportunity, and community impact." };

const education = [["Higher Education","Morehouse College TRIO Program","College access, academic readiness, and student-development programming."],["K–12 School System","Gwinnett County Public Schools","Student learning and future-ready pathway opportunities."],["K–12 School System","Fayette County Public Schools","Project-based STEAM and innovation engagement."],["Higher Education","Georgia Institute of Technology","Engineering, innovation, research, and talent development."],["Higher Education","Clark Atlanta University","Education, research, student pathways, and community impact."],["K–12 School System","Atlanta Public Schools","In-school and community-based STEAM programming."]];
const industry = [["Technology","Microsoft","Cloud, AI, digital skills, and technology ecosystem alignment."],["Artificial Intelligence","OpenAI","Generative AI tools and applied learning opportunities."],["Programming Partner","Metric Mate","Sports performance, data, AI-powered insight, and human-performance technology.","https://www.themetricmate.com/","/metric-mate-logo.jpg"],["Arts Education & Creative Media","FAM Incorporated","A nonprofit arts-education organization fostering unity and cross-cultural healing through films, educational forums, and community events.","https://www.famincorporated.org/","/fam-logo.png"],["Sports Technology","Soccer IQ Institute","Player development, safety, analytics, and technology-enabled sports learning.","https://www.socceriqinstitute.com/","/soccer-iq-logo.png"],["Healthcare & Sports Medicine","The ORTHO Project","Mentorship, education, career pathways, and sports-medicine innovation.","https://www.orthoproject.org/","/ortho-project.png"],["Civic & Community Innovation","The LEWIS Registry","Research, education, and community collaboration that build accountability, mutual respect, and stronger relationships between law enforcement and the communities they serve.","https://www.thelewisregistry.org/","/lewis-registry-logo.png"]];

function PartnerGrid({items}:{items:string[][]}){return <div className="network-grid">{items.map(([type,name,copy,url,logo])=><article key={name}><span>{type}</span>{logo&&(url?<a className="network-logo-link" href={url} target="_blank" rel="noopener noreferrer" aria-label={`Visit ${name}`}><img className={name === "The LEWIS Registry" ? "lewis-logo" : undefined} src={logo} alt={`${name} logo`}/></a>:<img src={logo} alt={`${name} logo`}/>)}<h3>{name}</h3><p>{copy}</p>{url&&<a href={url} target="_blank" rel="noopener noreferrer" aria-label={`Visit ${name}`}>Visit partner <span>↗</span></a>}</article>)}</div>}

export default function PartnersPage(){return <main><SiteHeader/><div id="main-content">
  <section className="subpage-hero partners-hero"><div><p className="eyebrow"><span>●</span> Innovation network</p><h1>Partnerships<br /><em>multiply impact.</em></h1></div><p>HBI’s network spans education, technology, healthcare, sports, civic leadership, and the creative industries.</p><div className="hero-index">NET</div></section>
  <section className="network-section"><div className="section-kicker"><span>01</span><p>School systems & education</p></div><div className="network-heading"><h2>Learning and talent-development partners.</h2><p>Partners create access to classrooms, expertise, research, pathways, and authentic challenges.</p></div><PartnerGrid items={education}/></section>
  <section className="network-section dark-network"><div className="section-kicker"><span>02</span><p>Industry & innovation</p></div><div className="network-heading"><h2>Technology, product, and programming partners.</h2><p>Industry collaborators bring platforms, subject-matter expertise, market context, and opportunities to build.</p></div><PartnerGrid items={industry}/></section>
  <section className="creative-network"><div><p className="eyebrow dark-eyebrow"><span>●</span> Community & creative industries</p><h2>Partners extending access and opportunity.</h2></div><div><span>Urban League of Greater Atlanta</span><span>Georgia Film Academy</span><span>Tyler Perry Studios</span><span>Dallas Austin Foundation</span><span>Boston University Theatre Program</span><span>Georgia Governor’s Office of Film</span></div></section>
  <section className="page-cta"><p className="eyebrow"><span>●</span> Join the network</p><h2>Bring your reach.<br /><em>Build shared value.</em></h2><a href="/contact">Explore a partnership <span>↗</span></a></section>
  </div><SiteFooter/></main>}
